### ISSUE TITLE
Error on local setup

### ISSUE THREAD

**Issue by MahmoudNasser01** [botpress/growth#24]
I followed all the instructions in the docs and faced this error (MAC OS):
npm run dev-local

> dev-local
> bp-integration-runner

node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

RequestError: connect ECONNREFUSED 127.0.0.1:4040
    at ClientRequest.<anonymous> (/Users/mahmoudnasser/side_work/chatbot/custom-llm/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/Users/mahmoudnasser/side_work/chatbot/custom-llm/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at emitErrorEvent (node:_http_client:104:11)
    at Socket.socketErrorListener (node:_http_client:512:5)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1734474099389,
    socket: 1734474099390,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1734474099390,
    abort: undefined,
    phases: {
      wait: 1,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 1
    }
  }
}

Node.js v23.3.0

**Comment by matthewbotpress** [comment]
Hey @MahmoudNasser01!

Are you still experiencing this?

**Comment by matthewbotpress** [comment]
Hey! So I tried to replicate your issue but it seems to be resolved with the latest updates (1.1.8 and now 1.2.0). If you encounter this issue again / any other issues please open another issue in this repository. I will be lurking! 👀 

Closing for the time being
